"""Single source of truth for image processing defaults."""

IMAGE_STORE_ORIGINAL_DEFAULT = False
IMAGE_OUTPUT_FORMAT_DEFAULT = "webp"
IMAGE_DISPLAY_MAX_EDGE_DEFAULT = 2048
IMAGE_DISPLAY_QUALITY_DEFAULT = 82
IMAGE_THUMB_MAX_EDGE_DEFAULT = 360
IMAGE_THUMB_QUALITY_DEFAULT = 70
