#!/usr/bin/env bash
set -euo pipefail

SKIP_INSTALL=0
SKIP_UI_BUILD=0
RELOAD=0
FRESH_SETUP=0

for arg in "$@"; do
  case "$arg" in
    --skip-install)
      SKIP_INSTALL=1
      ;;
    --skip-ui-build)
      SKIP_UI_BUILD=1
      ;;
    --reload)
      RELOAD=1
      ;;
    --fresh-setup)
      FRESH_SETUP=1
      ;;
    -h|--help)
      cat <<'EOF'
Usage: ./run.sh [options]

Options:
  --skip-install   Skip Python dependency installation
  --skip-ui-build  Skip UI build step
  --reload         Run uvicorn with auto-reload
  --fresh-setup    Remove local data/stowge.db before start
  -h, --help       Show this help
EOF
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      echo "Run ./run.sh --help for usage." >&2
      exit 1
      ;;
  esac
done

step() {
  echo
  echo "==> $1"
}

require_cmd() {
  local name="$1"
  local hint="$2"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "Required command '$name' is not available. $hint" >&2
    exit 1
  fi
}

new_random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr '+/' '-_' | tr -d '='
    return
  fi

  python3 - <<'PY'
import base64
import os
s = base64.b64encode(os.urandom(48)).decode('ascii')
print(s.replace('+', '-').replace('/', '_').rstrip('='))
PY
}

upsert_env_value() {
  local path="$1"
  local key="$2"
  local value="$3"

  if [[ ! -f "$path" ]]; then
    printf "%s=%s\n" "$key" "$value" >"$path"
    return
  fi

  if grep -qE "^${key}=" "$path"; then
    sed -i.bak -E "s|^${key}=.*$|${key}=${value}|" "$path"
    rm -f "$path.bak"
  else
    printf "\n%s=%s\n" "$key" "$value" >>"$path"
  fi
}

get_db_user_count() {
  local python_exe="$1"
  local db_path="$2"

  if [[ ! -f "$db_path" ]]; then
    echo 0
    return
  fi

  "$python_exe" - "$db_path" <<'PY'
import sqlite3
import sys

db_path = sys.argv[1]
conn = sqlite3.connect(db_path)
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='users'")
if cur.fetchone() is None:
    print(0)
else:
    cur.execute("SELECT COUNT(*) FROM users")
    print(cur.fetchone()[0])
conn.close()
PY
}

invoke_pip_filtered() {
  local python_exe="$1"
  shift

  set +e
  local output
  output=$("$python_exe" -m pip "$@" 2>&1)
  local exit_code=$?
  set -e

  while IFS= read -r line; do
    if [[ "$line" == Requirement\ already\ satisfied:* ]]; then
      continue
    fi
    echo "$line"
  done <<<"$output"

  if [[ $exit_code -ne 0 ]]; then
    echo "pip command failed with exit code $exit_code" >&2
    exit $exit_code
  fi
}

test_ui_build_required() {
  local ui_src_dir="$1"
  local ui_out_dir="$2"
  local python_cmd

  if [[ ! -d "$ui_out_dir" ]]; then
    return 0
  fi

  if command -v python3 >/dev/null 2>&1; then
    python_cmd="python3"
  else
    python_cmd="python"
  fi

  "$python_cmd" - "$ui_src_dir" "$ui_out_dir" <<'PY'
import os
import sys

ui_src_dir = sys.argv[1]
ui_out_dir = sys.argv[2]


def latest_mtime(root, skip_node_modules=False):
    latest = None
    for current_root, dirs, files in os.walk(root):
        if skip_node_modules:
            dirs[:] = [name for name in dirs if name != "node_modules"]
        for file_name in files:
            path = os.path.join(current_root, file_name)
            mtime = os.path.getmtime(path)
            if latest is None or mtime > latest:
                latest = mtime
    return latest


src_latest = latest_mtime(ui_src_dir, skip_node_modules=True)
out_latest = latest_mtime(ui_out_dir)

if out_latest is None:
    raise SystemExit(0)

if src_latest is None:
    raise SystemExit(1)

raise SystemExit(0 if src_latest > out_latest else 1)
PY
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
api_dir="$repo_root/api"
venv_dir="$api_dir/.venv"
python_exe="$venv_dir/bin/python"
requirements_file="$api_dir/requirements.txt"
ui_src_dir="$repo_root/ui"
ui_out_dir="$repo_root/ui/dist"
assets_dir="$repo_root/assets"
data_dir="$repo_root/data"
db_file="$data_dir/stowge.db"
env_file="$repo_root/.env"
ui_node_modules_dir="$ui_src_dir/node_modules"

step "Preparing environment"
if [[ ! -f "$env_file" ]]; then
  cat > "$env_file" <<'EOF'
# Auto-generated by run.sh on first run.
# Replace this with your own strong secret for persistent environments.
JWT_SECRET=change_me_to_a_long_random_string
EOF
  echo "Created default .env"
fi

jwt_value=""
if grep -qE '^JWT_SECRET=' "$env_file"; then
  jwt_value="$(grep -E '^JWT_SECRET=' "$env_file" | tail -n1 | cut -d'=' -f2-)"
fi

if [[ -z "$jwt_value" || "$jwt_value" == "change_me" || "$jwt_value" == "change_me_to_a_long_random_string" || ${#jwt_value} -lt 32 ]]; then
  step "Generating JWT secret in .env"
  upsert_env_value "$env_file" "JWT_SECRET" "$(new_random_secret)"
fi

step "Loading .env values"
set -a
# shellcheck disable=SC1090
source "$env_file"
set +a

step "Checking required tools"
require_cmd npm "Install Node.js (includes npm) from https://nodejs.org/"
if ! command -v python3 >/dev/null 2>&1 && ! command -v python >/dev/null 2>&1; then
  echo "Python is required. Install Python 3.12+ and ensure 'python3' or 'python' is on PATH." >&2
  exit 1
fi

if [[ ! -d "$venv_dir" ]]; then
  step "Creating API virtual environment"
  if command -v python3 >/dev/null 2>&1; then
    python3 -m venv "$venv_dir"
  else
    python -m venv "$venv_dir"
  fi
fi

if [[ ! -x "$python_exe" ]]; then
  echo "Python executable not found in venv: $python_exe" >&2
  exit 1
fi

if [[ $SKIP_INSTALL -eq 0 ]]; then
  step "Installing API dependencies"
  invoke_pip_filtered "$python_exe" install --upgrade pip
  invoke_pip_filtered "$python_exe" install -r "$requirements_file"
fi

if [[ $SKIP_UI_BUILD -eq 0 ]]; then
  ui_needs_dependencies=0
  ui_build_required=0

  if [[ ! -d "$ui_node_modules_dir" ]]; then
    ui_needs_dependencies=1
    ui_build_required=1
  elif test_ui_build_required "$ui_src_dir" "$ui_out_dir"; then
    ui_build_required=1
  fi

  if [[ $ui_build_required -eq 1 ]]; then
    step "Preparing UI build"
    pushd "$ui_src_dir" >/dev/null
    if [[ $ui_needs_dependencies -eq 1 ]]; then
      step "Installing UI dependencies (if needed)"
      if [[ -f "$ui_src_dir/package-lock.json" ]]; then
        npm ci
      else
        npm install
      fi
    fi

    step "Building UI"
    npm run build
    popd >/dev/null
  else
    step "Skipping UI build"
    echo "UI build output is already up to date."
  fi
fi

step "Preparing local data folders"
mkdir -p "$assets_dir" "$data_dir"

if [[ $FRESH_SETUP -eq 1 && -f "$db_file" ]]; then
  step "Fresh setup requested: removing local database"
  rm -f "$db_file"
fi

export UI_DIR="$ui_out_dir"
export ASSETS_DIR="$assets_dir"
if [[ -z "${DATABASE_DIR:-}" && -z "${DATABASE_URL:-}" ]]; then
  export DATABASE_DIR="$data_dir"
fi
if [[ -z "${JWT_ISSUER:-}" ]]; then
  export JWT_ISSUER="stowge"
fi

existing_users="$(get_db_user_count "$python_exe" "$db_file")"
if [[ "$existing_users" =~ ^[0-9]+$ ]] && [[ "$existing_users" -gt 0 ]]; then
  echo "Found $existing_users existing user(s) in local DB. Login mode will be shown."
  echo "Use --fresh-setup to reset only the local SQLite DB and show first-run admin setup again."
else
  echo "No users found in local DB. First-run admin setup will be shown."
fi

step "Starting Stowge at http://localhost:18090"
pushd "$api_dir" >/dev/null

uvicorn_args=("-m" "uvicorn" "stowge.main:app" "--host" "0.0.0.0" "--port" "18090" "--access-log")
if [[ $RELOAD -eq 1 ]]; then
  uvicorn_args+=("--reload")
fi

"$python_exe" "${uvicorn_args[@]}"
popd >/dev/null
